// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BoardDatum struct {
	ID    int32
	Name  string
	Value string
}

type Member struct {
	Cookie           pgtype.Text
	DateJoined       pgtype.Timestamptz
	Email            string
	ID               int64
	IsAdmin          pgtype.Bool
	LastChat         pgtype.Timestamp
	LastPost         pgtype.Timestamp
	LastSearch       pgtype.Timestamp
	LastView         pgtype.Timestamp
	Location         pgtype.Text
	PhotoUrl         pgtype.Text
	TotalThreadPosts pgtype.Int4
	TotalThreads     pgtype.Int4
}

type Thread struct {
	ID             int64
	MemberID       int64
	Subject        string
	DatePosted     pgtype.Timestamptz
	FirstPostID    pgtype.Int4
	Posts          pgtype.Int4
	Views          pgtype.Int4
	Sticky         pgtype.Bool
	Locked         pgtype.Bool
	LastMemberID   int64
	DateLastPosted pgtype.Timestamptz
	Indexed        bool
	Edited         bool
	Deleted        bool
}

type ThreadMember struct {
	MemberID      int64
	ThreadID      int64
	Undot         bool
	DatePosted    pgtype.Timestamp
	LastViewPosts int32
}

type ThreadPost struct {
	ID         int64
	ThreadID   int64
	DatePosted pgtype.Timestamptz
	MemberID   int64
	Indexed    bool
	Edited     bool
	Deleted    bool
	Body       pgtype.Text
}
