name: Build
on:
  push:
    branches: main
    paths:
      - "!README.md"
      - "!.github/workflows/golangci-lint.yml"
      - "!.github/workflows/test.yml"
      - "!.github/workflows/semgrep.yml"
      - "!.gitignore"
      - "!LICENSE"

  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tdiscuss
        uses: actions/checkout@v4
      - name: Build //cmd/tdiscuss
        run: |
          go build -o tdiscuss ./cmd/tdiscuss
