name: Test
run-name: Test
on:
  push:
  pull_request:
    paths:
      - "!README.md"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tdiscuss
        uses: actions/checkout@v3
      - name: Test //pkg/...
        run: |
          bazelisk test //pkg/...
