name: Build / test
run-name: Build / test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tdiscuss
        uses: actions/checkout@v3
      - name: Test //pkg/...
        run: |
          bazelisk test //pkg/...
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out tdiscuss
        uses: actions/checkout@v3
      - name: Build //cmd/tdiscuss
        run: |
          bazelisk build //cmd/tdiscuss:tdiscuss
